name: device_bot
description: A bot running on embedded devices, using OpenAI to interpret commands.
dependencies:
  discord:
    path: ../toit-discord
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  openai:
    path: ../toit-openai
